import React from 'react'
import Component from '../../Component'
function Telegu() {
  return (
		<div>
			<Component
				src="https://res.cloudinary.com/drbzxsbop/image/upload/v1694756298/g6_cpbjzk.jpg"
				title="Department of Telugu"
				para="--A Strong Regional Language--"
				para1="The Department of Telugu was established in the academic year 1975-76. B.A (E.M.S),B.Com (General), B.Com (Tax(A&F)), B.Com(Computers), B.Com(Honors), B.B.A, B.B.A-B.A, B.Sc (M.P.C), B.Sc (B.Z.C), B.Sc (M.P.Cs) B.Sc (CA.M.S) B.Sc (M.E.Cs) B.Sc (M.S.Cs), B.Sc (M.E.Cs) are undergraduate courses with Telugu as one of the subject and got autonomous status in the year 1988."
				para2="The department has highly qualified and well experienced teachers since its inception. Sri Nagalla Guru Prasada Rao, Sri Meka Narasimha Rao, Dr.Adusumelli Srinivasa Rao, Dr.Thati Srikrishna are faculty who worked and retired from the department. Sri Nagalla Guru Prasada Rao is a great teacher and an eminent critic in Telugu language and literature. His essays were widely published in many reputed Newspapers. He delivered many radio talks and did television programs in various channels .He presented Telugu literature and its greatness in a scholarly manner in many national and international forums. Sri Nagalla Guruprasada Rao is an established teacher and is praised by many linguists and language experts of not only Telugu but also of other languages. He rendered his services as a principal for PB SIDDARTHA COLLEGE OF ARTS AND SCIENCES and also as a chief secretary of SIDDARTHA KALAAPEETAM. He received prestigious BASHA SAMMAN AWARD sponsored by Kendra Sahithya Academy in 2017. Sri Meka Narasimha Rao served as a skilled public speaker from 1977 to 1993 and acted as head of the department, Telugu from 1993-1996.He is an inspiring teacher who shaped the department of Telugu as the best department. He taught not just the lessons to students but life. In his tenure as a head of the department many new courses were introduced .To mention a few Computer Science, Electronics, MBC,BBM,TAX,EEM etc., .For B.Com Tax and EEM unique syllabus is designed. Dr. Thati Sri Krishna rendered his services in Siddhartha degree college from 2000 to 2009.He manifested his expertise in Telugu literature. He is inspired by communist ideology. He published many of his essays and poems in various newspapers. He worked on a research project entitled VISAALANDRA NEWSPAPER-LITERARY SERVICEand published it Dr Adusumilli Srinivasa Rao joined degree college in 1996 by promotion .From 1996 July to 2010 he rendered his services as Head of the department Apart from heading the department he also took the responsibility of NSS wing and headed the department of DRAMATICS AND FINE ARTS. He acted as a convener for srujanosthsav and technical education He received state Best teacher award. He did a joint venture of UGC sponsored minor research project on VILLAGE DIETIES-WORSHIPS along with Sri K.Manamadha Rao Lecturer in Telugu and submitted to UGC"
				para3="At present Dr.Y.Vijayananda Raju is the Head, Department of Telugu. He is credit worthy of research and publications as well as highly inspirational teaching techniques in the field of Telugu. He is acting as subject expert in B.O.S of Dr.S.R.K Degree College,Yanam; Sir C R Reddy Degree College, Eluru and V.S.R& N.V.R.Degree College,Tenali. He recognized as research supervisor under Krishna University, Machilipatnam in the year 2016. The following research scholars are allotted under his supervision.

The other staff members of Telugu Department are Dr. Y.Purnachandra Rao and Sri.K.Manmadha Rao. Dr. Y.Purnachandra Rao is well-known poet who is awarded many honors from various literary institutions. He is also published many research papers in various journals. He is acting as subject expert in B.O.S of J.K.C. Degree College, Guntur; Maristella College, Vijayawada and S.D.M.S.Mahila Kalasala, Vijayawada. He received Best teacher award for 2013-2014 by Siddhartha Institutions.

          Sri K.Manmadha Rao is a best critic of literature and published many articles in the reputed jounals. He is acting as subject expert in B.O.S of Montissori Mahila Kalasala Vijayawada. Karnataka state open university,mysore.mysore university,mysore,regional college of education mysore and as a co-ordinator of Mummineni Subba Rao Siddhartha Kalapeetham."
				para4="The Department arranged Workshops, Seminars and Events in Telugu for Teachers and students by eminent personalities as resource persons. Dr.Garikipati Narasimha Rao, Mahasahsravadhani, Dr.Medasani Mohan, Panchasahasraavadhani, Dr.Paalaparthi Syamalananda Prasad, Avadhani, Brhma Sri Chaganti Koteswara Rao, Pravachanakartha, Saahiti Tapaswi Polavarapu Koteswara Rao, Story writer& Novelist, Sri Yandamoori Virendra Naadh, Story writer& Novelist, Prof.G.V.Subrahmanyam,Critic, Former V.C, Potti Sree Ramulu Telugu University, Hyderabad Prof. Bethavolu Ramabrahmam, Dean, University of Hyderabad, Prof.C. Ramanaiah, Former V.C, Dravidian University, Kuppam are some of the resource persons for the programmes organized in the department. The department trains newly admitted students for few days on basic grammar and literature before commencement of the prescribed syllabus and for academically weak students,the department conducts remedial classes and weekly tests to improve their performance.

The students of the department take active participation in cultural and social service activities to develop their personalities and leadership skills. V.N.Aditya (Cine Director),Sri Krishna (Playback Singer) sa silpa,riteesh(jamboo )(he was acted in balay balay balay chancelay program in maa tv) and Sumanth (Folk Singer) are some of the alumni of the department."
			/>
		</div>
	);
}

export default Telegu

