import React from "react";
import Component from "../../Component";
function Zoology() {
	return (
		<div>
			<Component
				src="https://res.cloudinary.com/drbzxsbop/image/upload/v1694756287/g5_vvtur1.jpg"
				title="Department of Zoology"
				para="-- Exploring the Wonders of Animal Life.--"
				para1="The Department of Zoology was established in 1979. It functions as a department which offers B.Sc. Zoology main (Core) with Chemistry and Botany as ancillary subjects from 1979 onwards. Dr.K.Kotaiah was the first Head of the department of Zoology in the college. He was followed by Dr.J.A.Prasad, Sri V.Babu Rao, and Sri. Ch.Venkateswarlu. Dr. V.D.Naidu and Sri A.Subba Rao and others contributed their services to the Department. Now the department is headed by Sri. Ch.Venkateswarlu with the faculty member Dr.K.Siva Prasad.
The Department of Zoology is one of the oldest Departments of P.B.Siddhartha College of Arts & Science. Being established in 1979, it had the rare privilege of becoming the first Science Department of the College. It started academic instructions at the Under Graduate level Zoology as major subject for undergraduate Programme of the Nagarjuna University. The College is now affiliated to the r Krishna University, Machilipatnam. Later the Department offered Undergraduate Programme B.Sc Zoology, Botany and Chemistry. The Programme was modeled on the Annual Evaluation System and the instruction was tailored to address the learning objectives defined in the syllabus. With the introduction of Choice Based Credit System the Department moved to more flexible and innovative space in terms of the form and content of the Programme. The new Programme is structured on Semester basis which runs through 3 years from the entry level. In addition to the affiliated Regular Programme the Department offers Certificate Course. The thrust for Research, despite its inherent constraints set by the undergraduate status, constitutes the significant highlight of the academic exercises of the Department."
				para2="The Department of Zoology was established in 1979. It functions as a department which offers B.Sc. Zoology main (Core) with Chemistry and Botany as ancillary subjects from 1979 onwards. Dr.K.Kotaiah was the first Head of the department of Zoology in the college. He was followed by Dr.J.A.Prasad, Sri V.Babu Rao, and Sri. Ch.Venkateswarlu. Dr. V.D.Naidu and Sri A.Subba Rao and others contributed their services to the Department. Now the department is headed by Sri. Ch.Venkateswarlu with the faculty member Dr.K.Siva Prasad.
The Department of Zoology is one of the oldest Departments of P.B.Siddhartha College of Arts & Science. Being established in 1979, it had the rare privilege of becoming the first Science Department of the College. It started academic instructions at the Under Graduate level Zoology as major subject for undergraduate Programme of the Nagarjuna University. The College is now affiliated to the r Krishna University, Machilipatnam. Later the Department offered Undergraduate Programme B.Sc Zoology, Botany and Chemistry. The Programme was modeled on the Annual Evaluation System and the instruction was tailored to address the learning objectives defined in the syllabus. With the introduction of Choice Based Credit System the Department moved to more flexible and innovative space in terms of the form and content of the Programme. The new Programme is structured on Semester basis which runs through 3 years from the entry level. In addition to the affiliated Regular Programme the Department offers Certificate Course. The thrust for Research, despite its inherent constraints set by the undergraduate status, constitutes the significant highlight of the academic exercises of the Department."
				para3="The Department stands for academic excellence in all respects. The faculty members are active in Research and have National and international Publications. So far the department has conducted many r Guest lectures, Training Programmes, Blood Typing Camps, Quiz Competitions, Remedial Coaching for students. The Department had conducted four National Seminars and one International seminar. Department had completed one minor project.

In the r 30 years of its existence, the department is credited for producing several Under-Graduate Studentr 550, pursued their Post-Graduate. Its alumni are doing exceptionally well as Scientists, Teachers and Technocrats at various Universities and Research laboratories in India and abroad. At present, the department has 100 B.Sc(B.Z.C) students."
				para4="The Department has been holding various workshops, symposia, conferences and other teaching courses to provide a platform for scientific exchanges. Keeping pace with time, the faculty members along with fellow colleagues from various colleges of the University revised B.Sc. Zoology syllabus in 2008. Department organizes workshops for college teachers to make them adept with current trends in various aspects of Animal Sciences.

The department has made remarkable strides during the past 30 years and is committed to continue working hard for excellence in Science."
			/>
		</div>
	);
}

export default Zoology;
